project_forum/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\KategoriController;
use App\Http\Controllers\PertanyaanController;
use App\Http\Controllers\JawabanController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\TinyMCEController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HomeController::class, 'home']);

Route::middleware('auth')->group(function () {
    //Create
    //Form Tambah Kategori
    Route::get('/kategori/create', [KategoriController::class, 'create']);
    //Untuk kirim data ke database atau tambah data ke database
    Route::post('/kategori', [KategoriController::class, 'store']);

    //Read
    //Menampilkan data
    Route::get('/kategori', [KategoriController::class, 'index']);
    //Detail Cast berdasarkan id
    Route::get('/kategori/{category_id}', [KategoriController::class, 'show']);

    // Edit Kategori
    Route::get('/kategori/{category_id}/edit', [KategoriController::class, 'edit']);
    //Update Kategori
    Route::put('/kategori/{category_id}', [KategoriController::class, 'update']);
    // Delete Kategori
    Route::delete('/kategori/{category_id}', [KategoriController::class, 'destroy']);

    //Profile
    Route::resource('profile', ProfileController::class)->only(['index', 'update']);
});

//CRUD Pertanyaan
Route::resource('/pertanyaan', PertanyaanController::class);

//CRUD Jawaban
// Tambah Jawaban
Route::post('/jawaban/{pertanyaan_id}', [JawabanController::class, 'tambah']);
// Edit Jawaban
Route::get('/jawaban/{jawaban_id}/edit', [JawabanController::class, 'edit']);
//Update Jawaban
Route::put('/jawaban/{jawaban_id}', [JawabanController::class, 'update']);
// Delete Jawaban
Route::delete('/jawaban/{jawaban_id}', [JawabanController::class, 'destroy']);

// CRUD Login
Auth::routes();

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

project_forum/app/Models/Pertanyaan.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Pertanyaan extends Model
{
    use HasFactory;

    protected $table = 'pertanyaan';

    protected $fillable = ['judul', 'gambar', 'content' , 'date', 'category_id'];

    public function kategori()
    {
        return $this->belongsTo(Kategori::class, 'category_id');
    }

    public function jawaban()
    {
        return $this->hasMany(Jawaban::class, 'pertanyaan_id');
    }
}

project_forum/app/Http/Controllers/PertanyaanController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Kategori;
use App\Models\Pertanyaan;
use Illuminate\Support\Facades\DB;
use File;
use RealRashid\SweetAlert\Facades\Alert;
use Jenssegers\Date\Date;

class PertanyaanController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('auth')->except(['index', 'show']);
    }

    public function index()
    {
        $pertanyaan = Pertanyaan::get();
        $title = 'Delete Pertanyaan!';
        $text = "Apakah anda yakin ingin menghapusnya?";
        confirmDelete($title, $text);

        return view('pertanyaan.index', ['pertanyaan' => $pertanyaan]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Kategori::get();

        return view('pertanyaan.createpertanyaan', ['category' => $categories]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    
     public function store(Request $request)
    {
        
        $request->validate([
            'category_id' => 'required',
            'judul' => 'required',
            'gambar' => 'required|image|mimes:jpg,png,jpeg',
            'content' => 'required',
            'date' => 'required|date',
        ]);

        $fileName = time() . '.' . $request->gambar->extension();
        $request->gambar->move(public_path('image'), $fileName);

        // Convert the date to a Jenssegers/Date instance
        $date = Date::createFromFormat('Y-m-d', $request->input('date'));
        
        $pertanyaan = new Pertanyaan();
        $pertanyaan->category_id = $request->category_id;
        $pertanyaan->judul = $request->judul;
        $pertanyaan->gambar = $fileName;
        $pertanyaan->content = $request->content;
        $pertanyaan->date = $date; // Use Jenssegers/Date instance directly
        
        $pertanyaan->save();

        Alert::success('Berhasil', 'Berhasil Menambahkan Pertanyaan');

        return redirect('/pertanyaan');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $pertanyaan = Pertanyaan::find($id);

        return view('pertanyaan.detail', ['pertanyaan' => $pertanyaan]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $categories = Kategori::all();
        $pertanyaan = Pertanyaan::find($id);

        return view('pertanyaan.editPertanyaan', ['pertanyaan' => $pertanyaan, 'category' => $categories]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'category_id' => 'required',
            'judul' => 'required',
            'gambar' => 'mimes:jpg,png,jpeg',
            'content' => 'required',
            'date' => 'required'
        ]);

        $pertanyaan = Pertanyaan::find($id);

        if ($request->has('image')) {
            $path = 'image/';
            File::delete($path . $pertanyaan->image);

            $fileName = time() . '.' . $request->gambar->extension();
            $request->gambar->move(public_path('image'), $fileName);

            $pertanyaan->image = $fileName;
        }

        $pertanyaan->category_id = $request->category_id;
        $pertanyaan->judul = $request->judul;
        $pertanyaan->content = $request->content;
        $pertanyaan->date = $request->date;

        $pertanyaan->save();

        Alert::success('Berhasil', 'Berhasil Merubah Pertanyaan');

        return redirect('/pertanyaan');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $pertanyaan = Pertanyaan::find($id);
    
        $path = 'image/';
        File::delete($path . $pertanyaan->image);
    
        $pertanyaan->delete();
    
        return redirect('/pertanyaan');
    }
    
}

project_forum/resources/views/pertanyaan/createpertanyaan.blade.php
@extends('layout.master')

@section('judul')
Tambah Pertanyaan
@endsection

@section('content')

<form action="/pertanyaan" method="POST" enctype="multipart/form-data">
    @csrf

    <div class="form-group">
        <label for="exampleFormControlSelect1">Kategori</label>
        <select name="category_id" class="form-control" id="">
            <option value="">--pilih kategori--</option>
            @forelse ($category as $item)
                <option value="{{$item->id}}"> {{$item->name}} </option>
            @empty
                <option value="">Kategori tidak ditemukan</option>
            @endforelse
        </select>
    </div>
    @error('category_id')
        <div class="alert alert-danger">{{ $message }}</div>
    @enderror

    <div class="form-group">
        <label>Judul</label>
        <input type="text" name="judul" class="form-control">
    </div>
    @error('judul')
        <div class="alert alert-danger">{{ $message }}</div>
    @enderror

    <div class="form-group">
        <label>Pertanyaan</label>
        <textarea name="content" class="form-control" cols="30" rows="10"></textarea>
    </div>
    @error('content')
        <div class="alert alert-danger">{{ $message }}</div>
    @enderror

    <div class="form-group">
        <label>Tanggal</label>
        <input type="date" name="date" class="form-control">
    </div>
    @error('date')
        <div class="alert alert-danger">{{ $message }}</div>
    @enderror

    <div class="form-group">
        <label>Gambar (Image)</label>
        <input type="file" name="gambar" class="form-control">
    </div>
    @error('gambar')
        <div class="alert alert-danger">{{ $message }}</div>
    @enderror
        
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

@push('scripts')
<script src="https://cdn.tiny.cloud/1/uyhg8uh495t7usovbokf6xfv85apks9g0nlkrma2ov65ecda/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>
<script>
    tinymce.init({
        selector: 'textarea',
        plugins: 'ai tinycomments mentions anchor autolink charmap codesample emoticons image link lists media searchreplace table visualblocks wordcount checklist mediaembed casechange export formatpainter pageembed permanentpen footnotes advtemplate advtable advcode editimage tableofcontents mergetags powerpaste tinymcespellchecker autocorrect a11ychecker typography inlinecss',
        toolbar: 'undo redo | blocks fontfamily fontsize | bold italic underline strikethrough | link image media table mergetags | align lineheight | tinycomments | checklist numlist bullist indent outdent | emoticons charmap | removeformat',
        tinycomments_mode: 'embedded',
        tinycomments_author: 'Author name',
        mergetags_list: [
            { value: 'First.Name', title: 'First Name' },
            { value: 'Email', title: 'Email' },
        ],
        ai_request: (request, respondWith) => respondWith.string(() => Promise.reject("See docs to implement AI Assistant")),
    });
</script>
  
@endpush

@endsection

project_forum/resources/views/pertanyaan/detail.blade.php
@extends('layout.master')

@section('judul')
Halaman Pertanyaan
@endsection

@section('content')
<img class="card-img-top" src="{{ asset('image/' . $pertanyaan->gambar) }}" alt="...">
<h3>{{ $pertanyaan->judul }}</h3>
<p class="card-text">{!! $pertanyaan->content !!}</p>

<hr>

<h4>List Jawaban</h4>
@forelse ($pertanyaan->jawaban as $item)
<div id="accordion">
    <div class="card">
        <div class="card-header" id="headingOne">
            <h5 class="mb-0">
                <button class="btn btn-link" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true"
                    aria-controls="collapseOne">
                    Jawaban dari {{$item->user->username}}
                </button>

            </h5>
        </div>

        <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordion">
            <div class="card-body">
                {!! $item->content !!}
                <form action="/jawaban/{{$item->id}}" method="POST">
                    @csrf
                    @method('DELETE')
                    <a href="/jawaban/{{$item->id}}/edit" class="btn btn-warning btn-sm">Edit</a>
                    <input type="submit" value="Delete" class="btn btn-danger btn-sm">
                </form>
            </div>

        </div>
    </div>

    @empty
    <h4>Belum ada Jawaban</h4>
    @endforelse

    <br><br>
    <h3>Isi Jawabanmu </h3>
    <form action="/jawaban/{{ $pertanyaan->id }}" method="post"> <!-- Corrected the form opening tag -->
        @csrf
        <textarea name="content" cols="30" class="form-control my-3" placeholder="Isi Jawaban" rows="10"></textarea>
        @error('content')
        <div class="alert alert-danger">
            {{ $message }}
        </div>
        @enderror
        <br>
        <input type="submit" class="btn btn-primary btn-block btn-sm" value="Jawab">
    </form> <!-- Corrected the form closing tag -->
    @push('scripts')
    <script src="https://cdn.tiny.cloud/1/uyhg8uh495t7usovbokf6xfv85apks9g0nlkrma2ov65ecda/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>
<script>
    tinymce.init({
        selector: 'textarea',
        plugins: 'ai tinycomments mentions anchor autolink charmap codesample emoticons image link lists media searchreplace table visualblocks wordcount checklist mediaembed casechange export formatpainter pageembed permanentpen footnotes advtemplate advtable advcode editimage tableofcontents mergetags powerpaste tinymcespellchecker autocorrect a11ychecker typography inlinecss',
        toolbar: 'undo redo | blocks fontfamily fontsize | bold italic underline strikethrough | link image media table mergetags | align lineheight | tinycomments | checklist numlist bullist indent outdent | emoticons charmap | removeformat',
        tinycomments_mode: 'embedded',
        tinycomments_author: 'Author name',
        mergetags_list: [
            { value: 'First.Name', title: 'First Name' },
            { value: 'Email', title: 'Email' },
        ],
        ai_request: (request, respondWith) => respondWith.string(() => Promise.reject("See docs to implement AI Assistant")),
    });
</script>

    @endpush
    <hr><br>
    <a href="/pertanyaan" class="btn btn-secondary btn-block btn-sm">Kembali</a>
    @endsection

project_forum/resources/views/pertanyaan/editJawaban.blade.php
@extends('layout.master')

@section('judul')
Edit Jawaban
@endsection

@section('content')
<form action="/jawaban/{{$jawaban->id}}" method="POST">
    @csrf
    @method('put')
    <div class="form-group">
        <label>Isi Jawaban</label>
        <textarea  name="content" class="form-control" cols="30" rows="10">{{$jawaban->content}}"</textarea>
    </div>
    @error('name')
    <div class="alert alert-danger">{{ $message }}</div>
    @enderror

    <button type="submit" class="btn btn-warning">Update</button>
</form>
@endsection

project_forum/resources/views/pertanyaan/editPertanyaan.blade.php
@extends('layout.master')

@section('judul')
Edit Pertanyaan
@endsection

@section('content')

<form action="/pertanyaan/{{$pertanyaan->id}}" method="POST" enctype="multipart/form-data">
    @csrf
    @method('put')
    <div class="form-group">
        <label>Kategori</label>
        <select name="category_id" class="form-control">
            <option value="">--pilih kategori--</option>
            @foreach ($category as $item)
            @if ($item->id == $pertanyaan->category_id)
            <option value="{{$item->id}}"> {{$item->name}} </option>
            @else
            <option value="{{$item->id}}"> {{$item->name}} </option>
            @endif
            @endforeach
        </select>
    </div>
    @error('category_id')
    <div class="alert alert-danger">{{ $message }}</div>
    @enderror

    <div class="form-group">
        <label>Judul</label>
        <input type="text" name="judul" value="{{$pertanyaan->judul}}" class="form-control">
    </div>
    @error('judul')
    <div class="alert alert-danger">{{ $message }}</div>
    @enderror

    <div class="form-group">
        <label>Pertanyaan</label>
        <textarea name="content" class="form-control" cols="30" rows="10">{{$pertanyaan->content}}</textarea>
    </div>
    @error('content')
    <div class="alert alert-danger">{{ $message }}</div>
    @enderror

    <div class="form-group">
        <label>Tanggal</label>
        <input type="date" name="date" class="form-control">
    </div>
    @error('date')
    <div class="alert alert-danger">{{ $message }}</div>
    @enderror

    <div class="form-group">
        <label>Gambar (Image)</label>
        <input type="file" name="gambar" class="form-control">
    </div>
    @error('gambar')
    <div class="alert alert-danger">{{ $message }}</div>
    @enderror

    <button type="submit" class="btn btn-primary">Submit</button>
</form>

@endsection

project_forum/resources/views/pertanyaan/index.blade.php
@extends('layout.master')

@section('judul')
    Halaman List Pertanyaan
@endsection

@section('content')
    
@auth
<a href="/pertanyaan/create" class="btn btn-primary btn-sm mb-4">Tambah Pertanyaan</a>
@endauth
        <div class="row">
            @forelse ($pertanyaan as $item)
                <div class="col-md-4 mb-4">
                    <div class="card">
                        <img class="card-img-top" src="{{ asset('image/' . $item->gambar) }}" alt="..." height="250px">
                        <div class="card-body">
                            <h3>{{ $item->judul }}</h3>
                            <span class="badge badge-info">{{$item->kategori->name}}</span>
                            <p class="card-text" >{!! Str::limit ($item->content, 50) !!}</p>
                            <a href="{{ route('pertanyaan.show', $item->id) }}" class="btn btn-secondary btn-block btn-sm">More</a>
                            @auth
                            <div class="row my-3">
                                <div class="col">
                                    <a href="{{ route('pertanyaan.edit', $item->id) }}" class="btn btn-warning btn-block btn-sm">Edit</a>
                                </div>
                                <div class="col">
                                    <form action="{{ route('pertanyaan.destroy', $item->id) }}" method="POST">
                                        @csrf
                                        @method('DELETE')
                                        <a href="{{ route('pertanyaan.destroy', $item->id) }}" class="btn btn-danger btn-block btn-sm" data-confirm-delete="true">Delete</a>
                                    </form>
                                </div>
                            </div>
                            @endauth
                        </div>
                    </div>
                </div>
            @empty
                <div class="col-12">
                    <h2 class="text-center">Tidak ada Pertanyaan</h2>
                </div>
            @endforelse
        </div>
    </div>
@endsection